### ISSUE TITLE
Call to undefined method Brick\\Math\\BigInteger::getX()

### ISSUE THREAD

**Issue by metalsadman** [laravel-notification-channels/webpush#137]
Pushing notification gives Error log:
```bash
"message": "Call to undefined method Brick\\Math\\BigInteger::getX()",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "E:\\laravel-web-push-demo\\vendor\\minishlink\\web-push\\src\\Encryption.php",
    "line": 99,
...
```
https://github.com/web-push-libs/web-push-php/issues/295
Laravel Framework 6.18.0
webpush: latest

**Comment by jamesbhatta** [comment]
I am getting the same issue as well after `composer update`

**Comment by martijnb92** [comment]
It is fixed!

**Comment by metalsadman** [comment]
> It is fixed!

how to get the fix? or is the dependency on this lib auto updates from the latest update on web-push?

**Comment by martijnb92** [comment]
> > It is fixed!
> 
> how to get the fix? or is the dependency on this lib auto updates from the latest update on web-push?

Run `composer update`

**Comment by metalsadman** [comment]
> > > It is fixed!
> > 
> > 
> > how to get the fix? or is the dependency on this lib auto updates from the latest update on web-push?
> 
> Run `composer update`

i get a `"Notification sent."` response, but the notification still doesn't update.

**Comment by martijnb92** [comment]
> > > > It is fixed!
> > > 
> > > 
> > > how to get the fix? or is the dependency on this lib auto updates from the latest update on web-push?
> > 
> > 
> > Run `composer update`
> 
> i get a `"Notification sent."` response, but the notification still doesn't update.

Check the comments on the fix, you are probably using windows. There is a bug in this version, not all notifications arrive. This will be fixed.

**Comment by metalsadman** [comment]
> > > > > It is fixed!
> > > > 
> > > > 
> > > > how to get the fix? or is the dependency on this lib auto updates from the latest update on web-push?
> > > 
> > > 
> > > Run `composer update`
> > 
> > 
> > i get a `"Notification sent."` response, but the notification still doesn't update.
> 
> Check the comments on the fix, you are probably using windows. There is a bug in this version, not all notifications arrive. This will be fixed. At least there are no longer any errors. Or use the V5 version via composer.

yes i'm on windows, which V5 version do you  mean?
